create schema if not exists private;
revoke all on schema private from public;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  is_member boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) between 1 and 64),
  color_class text not null default 'category-gold' check (
    color_class in (
      'category-gold', 'category-rose', 'category-violet',
      'category-cyan', 'category-green', 'category-slate'
    )
  ),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.courses (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  title text not null check (length(btrim(title)) between 1 and 255),
  summary text not null default '',
  cover text not null default '',
  learners integer not null default 0 check (learners >= 0),
  views bigint not null default 0 check (views >= 0),
  is_member_only boolean not null default false,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.course_contents (
  course_id bigint primary key references public.courses(id) on delete cascade,
  feishu_doc_url text not null check (length(btrim(feishu_doc_url)) between 8 and 1024),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index courses_category_id_idx on public.courses(category_id);
create index courses_published_sort_idx
  on public.courses(sort_order, id) where is_published;
create index profiles_role_idx on public.profiles(role) where role = 'admin';

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();
create trigger categories_set_updated_at
before update on public.categories
for each row execute function private.set_updated_at();
create trigger courses_set_updated_at
before update on public.courses
for each row execute function private.set_updated_at();
create trigger course_contents_set_updated_at
before update on public.course_contents
for each row execute function private.set_updated_at();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin' and is_active
  );
$$;

create or replace function private.is_active_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and is_active
      and (is_member or role = 'admin')
  );
$$;

revoke all on function private.is_admin() from public;
revoke all on function private.is_active_member() from public;
grant usage on schema private to anon, authenticated;
grant execute on function private.is_admin() to anon, authenticated;
grant execute on function private.is_active_member() to authenticated;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.courses enable row level security;
alter table public.course_contents enable row level security;

create policy profiles_select_self_or_admin
on public.profiles for select
to authenticated
using ((select auth.uid()) = id or (select private.is_admin()));

create policy profiles_update_admin
on public.profiles for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy categories_select_visible
on public.categories for select
to anon, authenticated
using (is_active or (select private.is_admin()));

create policy categories_insert_admin
on public.categories for insert
to authenticated
with check ((select private.is_admin()));
create policy categories_update_admin
on public.categories for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));
create policy categories_delete_admin
on public.categories for delete
to authenticated
using ((select private.is_admin()));

create policy courses_select_visible
on public.courses for select
to anon, authenticated
using (is_published or (select private.is_admin()));

create policy courses_insert_admin
on public.courses for insert
to authenticated
with check ((select private.is_admin()));
create policy courses_update_admin
on public.courses for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));
create policy courses_delete_admin
on public.courses for delete
to authenticated
using ((select private.is_admin()));

create policy course_contents_select_entitled
on public.course_contents for select
to authenticated
using (
  exists (
    select 1
    from public.courses c
    join public.profiles p on p.id = (select auth.uid())
    where c.id = course_contents.course_id
      and p.is_active
      and (c.is_published or p.role = 'admin')
      and (not c.is_member_only or p.is_member or p.role = 'admin')
  )
);

create policy course_contents_insert_admin
on public.course_contents for insert
to authenticated
with check ((select private.is_admin()));
create policy course_contents_update_admin
on public.course_contents for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));
create policy course_contents_delete_admin
on public.course_contents for delete
to authenticated
using ((select private.is_admin()));

grant select on public.profiles to authenticated;
grant update (display_name, role, is_member, is_active) on public.profiles to authenticated;
grant select on public.categories, public.courses to anon, authenticated;
grant select on public.course_contents to authenticated;
grant insert, update, delete on public.categories, public.courses, public.course_contents to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all on public.profiles, public.categories, public.courses, public.course_contents to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.increment_course_views_internal(target_course_id bigint)
returns bigint
language sql
security invoker
set search_path = ''
as $$
  update public.courses
  set views = views + 1
  where id = target_course_id
  returning views;
$$;

revoke all on function public.increment_course_views_internal(bigint) from public, anon, authenticated;
grant execute on function public.increment_course_views_internal(bigint) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'course-covers',
  'course-covers',
  true,
  4194304,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy course_covers_public_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'course-covers');

create policy course_covers_admin_insert
on storage.objects for insert
to authenticated
with check (bucket_id = 'course-covers' and (select private.is_admin()));
create policy course_covers_admin_update
on storage.objects for update
to authenticated
using (bucket_id = 'course-covers' and (select private.is_admin()))
with check (bucket_id = 'course-covers' and (select private.is_admin()));
create policy course_covers_admin_delete
on storage.objects for delete
to authenticated
using (bucket_id = 'course-covers' and (select private.is_admin()));

insert into public.categories (name, color_class, sort_order)
values
  ('基础课', 'category-gold', 1),
  ('系统课', 'category-rose', 2),
  ('AI Coding', 'category-gold', 3),
  ('AI Agent', 'category-violet', 4)
on conflict (name) do nothing;

with seed(title, category_name, summary, cover, learners, views, member_only, sort_order, url) as (
  values
    ('社群使用说明书', '基础课', '进入社群后需要做些什么，社群课程内容如何学习，福利、权益如何领取', '/images/zhenganhuo/platform/courses/20260704011901-e1f8c89b3c37a12d.png', 143, 512, false, 1, 'https://feishu.cn/docx/NovaCommunityGuideDemo'),
    ('小白 AI 通识', '基础课', 'AI 基础知识通识', '/images/zhenganhuo/platform/courses/20260702021804-23eff75c1282352a.jpg', 101, 1080, false, 2, 'https://feishu.cn/docx/NovaAiBasicsDemo'),
    ('Codex从小白到专家', '系统课', '从零开始，系统学习Codex', '/images/zhenganhuo/platform/courses/20260709182916-9aef42664d538784.png', 130, 1195, true, 3, 'https://feishu.cn/docx/NovaCodexCourseDemo'),
    ('AI 智能体串讲', '系统课', '从 0 到 1 入门 AI Agent 智能体，文档课程，建议快速通读了解即可。', '/images/zhenganhuo/platform/courses/20260702024718-0c62fad9ef1e8817.jpg', 61, 616, true, 4, 'https://feishu.cn/docx/NovaAgentIntroDemo'),
    ('AI 编程', 'AI Coding', '黄叔讲解 AI 编程的课程，后续会进行重构拆解', '/images/zhenganhuo/platform/courses/20260702024125-6afb170b465be54d.jpg', 44, 367, true, 5, 'https://feishu.cn/docx/NovaAiCodingDemo'),
    ('AI Skills', 'AI Agent', 'AI skills系统课程，后期拆解重构', '/images/zhenganhuo/platform/courses/20260702024259-0507cce3ca683f52.jpg', 83, 730, true, 6, 'https://feishu.cn/docx/NovaAiSkillsDemo')
), inserted as (
  insert into public.courses (title, category_id, summary, cover, learners, views, is_member_only, sort_order)
  select s.title, c.id, s.summary, s.cover, s.learners, s.views, s.member_only, s.sort_order
  from seed s join public.categories c on c.name = s.category_name
  where not exists (select 1 from public.courses existing where existing.title = s.title)
  returning id, title
)
insert into public.course_contents (course_id, feishu_doc_url)
select i.id, s.url
from inserted i join seed s on s.title = i.title;
