create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  page text not null check (page in ('events', 'cases')),
  title text not null check (length(btrim(title)) between 1 and 255),
  summary text not null default '',
  category text not null default '',
  category_class text not null default 'category-gold' check (
    category_class in (
      'category-gold', 'category-rose', 'category-violet',
      'category-cyan', 'category-green', 'category-slate'
    )
  ),
  tags text[] not null default '{}',
  cover text not null default '',
  learners integer not null default 0 check (learners >= 0),
  views bigint not null default 0 check (views >= 0),
  cta text not null default '',
  is_member_only boolean not null default true,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  href text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_items_page_title_unique unique (page, title),
  check (array_length(tags, 1) is null or array_length(tags, 1) <= 4)
);

create index if not exists catalog_items_page_sort_idx
  on public.catalog_items(page, sort_order, id) where is_published;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'catalog_items_set_updated_at'
  ) then
    create trigger catalog_items_set_updated_at
    before update on public.catalog_items
    for each row execute function private.set_updated_at();
  end if;
end $$;

alter table public.catalog_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'catalog_items'
      and policyname = 'catalog_items_select_visible'
  ) then
    create policy catalog_items_select_visible
    on public.catalog_items for select
    to anon, authenticated
    using (is_published or (select private.is_admin()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'catalog_items'
      and policyname = 'catalog_items_insert_admin'
  ) then
    create policy catalog_items_insert_admin
    on public.catalog_items for insert
    to authenticated
    with check ((select private.is_admin()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'catalog_items'
      and policyname = 'catalog_items_update_admin'
  ) then
    create policy catalog_items_update_admin
    on public.catalog_items for update
    to authenticated
    using ((select private.is_admin()))
    with check ((select private.is_admin()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'catalog_items'
      and policyname = 'catalog_items_delete_admin'
  ) then
    create policy catalog_items_delete_admin
    on public.catalog_items for delete
    to authenticated
    using ((select private.is_admin()));
  end if;
end $$;

grant select on public.catalog_items to anon, authenticated;
grant insert, update, delete on public.catalog_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all on public.catalog_items to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.catalog_items
  (page, title, summary, category, category_class, tags, cover, learners, views, cta, is_member_only, sort_order)
values
  (
    'events',
    '第一届Skills 黑客松（上）',
    '第一届社群黑客松活动，第一天',
    '黑客松',
    'category-green',
    array['黑客松', '活动', '会员专享', '38人'],
    'https://agentwork.oss-cn-beijing.aliyuncs.com/agentworks/covers/content/202607/20260702034107-2852d92664558bb3.jpg',
    38,
    77,
    '会员专享',
    true,
    1
  ),
  (
    'events',
    '第一届 Skills 黑客松（下）',
    '第二天',
    '黑客松',
    'category-green',
    array['黑客松', '活动', '会员专享', '6人'],
    'https://agentwork.oss-cn-beijing.aliyuncs.com/agentworks/covers/content/202607/20260704002453-e6fe99f42d9dbcbb.jpg',
    6,
    16,
    '会员专享',
    true,
    2
  ),
  (
    'events',
    '第二届 Skills 黑客松（上）',
    '第二届社群 Skills 大赛',
    '黑客松',
    'category-green',
    array['黑客松', '活动', '会员专享', '8人'],
    'https://agentwork.oss-cn-beijing.aliyuncs.com/agentworks/covers/content/202607/20260707154304-440b284fd8334354.jpg',
    8,
    18,
    '会员专享',
    true,
    3
  ),
  (
    'events',
    '第二届 Skills 黑客松（下）',
    '第二天',
    '黑客松',
    'category-green',
    array['黑客松', '活动', '会员专享', '16人'],
    'https://agentwork.oss-cn-beijing.aliyuncs.com/agentworks/covers/content/202607/20260707155545-47f69ac35752c5bc.jpg',
    16,
    34,
    '会员专享',
    true,
    4
  ),
  (
    'cases',
    '电商运营，独立开发商品图生成工具',
    '38岁非技术的前电商运营人，靠vibe coding，从月入3千到变现10W+只用了四个月',
    '商业化',
    'category-rose',
    array['商业化', 'AI', '案例', '会员专享'],
    '/images/front-design/case-commerce-cover.png',
    60,
    135,
    '会员专享',
    true,
    1
  )
on conflict (page, title) do nothing;
